config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :sessions, only: [:create]
  resources :warriors, only: [:create]
  
  get 'signup', to: 'warriors#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/warrior.rb
class Warrior < ApplicationRecord
  has_secure_password

  validates :name, presence: true, uniqueness: true

  scope :online, -> { where(is_online: true) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_warrior

  def current_warrior
    @current_warrior ||= Warrior.find_by(id: session[:warrior_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @online_warriors = Warrior.online
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    warrior = Warrior.find_by(name: params[:name])
    if warrior && warrior.authenticate(params[:password])
      session[:warrior_id] = warrior.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Name or password is invalid!"
      render :new
    end
  end

  def destroy
    session[:warrior_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/warriors_controller.rb
class WarriorsController < ApplicationController
  # GET /warriors/new
  def new
    @warrior = Warrior.new
  end

  # POST /warriors
  def create
    @warrior = Warrior.new(warrior_params)

    respond_to do |format|
      if @warrior.save
        format.html { redirect_to root_path, notice: 'Signup complete!' }
      else
        format.html { render :new }
      end
    end
  end

  private
    
  def warrior_params
    params.require(:warrior).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/warriors_helper.rb
module WarriorsHelper
end

app/views/home/index.html.erb
<h1>Game "Warriors"</h1>

<h2>Online warriors:</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <% @online_warriors.each do |warrior| %>
      <tr>
        <td><%= warrior.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mygame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'shared/login_or_signup' %>
    <%= render partial: 'shared/navigation_menu' %>
    <p id="alert"><%= alert %></p>
    <p id="notice"><%= notice %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_login_or_signup.html.erb
<% if current_warrior %>
  Logged in as <%= current_warrior.name %>
  <%= link_to "Log Out", logout_path %>
<% else %>
  <%= link_to "Sign Up", signup_path %>
  <%= link_to "Log In", login_path %>
<% end %>

app/views/shared/_navigation_menu.html.erb
<p><%= link_to 'Home', root_path %></p>

app/views/warriors/_form.html.erb
<%= form_with(model: warrior, local: true) do |form| %>
  <% if warrior.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(warrior.errors.count, "error") %> prohibited this warrior from being saved:</h2>

      <ul>
      <% warrior.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/warriors/new.html.erb
<h1>New Warrior</h1>

<%= render 'form', warrior: @warrior %>

<%= link_to 'Back', warriors_path %>